version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://db:5432/betdb
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: betdb
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 60

  frontend:
    build:
      context: "C:/Users/HP/webowka/peniaczki_ztw/pewniaczki_ztw"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"